pairs = [
    ('Show me ad for AAPL.', 'GetTimeSeriesAd'),
]

pairs_ = [
    # ('Show me ad for AAPL.', 'GetTimeSeriesAd'),
    # ('Show me add for AAPL.', 'GetTimeSeriesAdd'),
    # ('Show me adosc for AAPL.', 'GetTimeSeriesAdOsc'),
    # ('Show me adx for AAPL.', 'GetTimeSeriesAdx'),
    # ('Show me adxr for AAPL.', 'GetTimeSeriesAdxr'),
    # ('Show me analyst ratings - light for AAPL.', 'GetAnalystRatingsLight'),
    ('Show me analyst ratings - us equities for AAPL.', 'GetAnalystRatingsUsEquities'),  # fixed-error
    ('How many API requests have I made in the last minute', 'GetApiUsage'),  # fixed-error
    # ('Show me apo for AAPL.', 'GetTimeSeriesApo'),
    # ('Show me aroon for AAPL.', 'GetTimeSeriesAroon'),

    # ('Show me aroonosc for AAPL.', 'GetTimeSeriesAroonOsc'),
    # ('Show me atr for AAPL.', 'GetTimeSeriesAtr'),
    # ('Show me avg for AAPL.', 'GetTimeSeriesAvg'),
    # ('Show me avgprice for AAPL.', 'GetTimeSeriesAvgPrice'),
    # ('Show me balance sheet for AAPL.', 'GetBalanceSheet'),
    # ('Show me balance sheet consolidated for AAPL.', 'GetBalanceSheetConsolidated'),
    # # ('Show me batches for AAPL.', 'advanced'),  # skipped-error,
    # ('Show me bbands for AAPL.', 'GetTimeSeriesBBands'),
    # ('Show me beta for AAPL.', 'GetTimeSeriesBeta'),
    ('Show me bonds list for AAPL.', 'GetBonds'),  # fixed-error

    # ('Show me bop for AAPL.', 'GetTimeSeriesBop'),
    # ('Show me cash flow for AAPL.', 'GetCashFlow'),
    # ('Show me cash flow consolidated for AAPL.', 'GetCashFlowConsolidated'),
    # ('Show me cci for AAPL.', 'GetTimeSeriesCci'),
    # ('Show me ceil for AAPL.', 'GetTimeSeriesCeil'),
    # ('Show me cmo for AAPL.', 'GetTimeSeriesCmo'),
    ('Show me commodities list for AAPL.', 'GetCommodities'),  # fixed-error
    # ('Show me coppock for AAPL.', 'GetTimeSeriesCoppock'),
    # ('Show me correl for AAPL.', 'GetTimeSeriesCorrel'),
    # ('Show me countries list for AAPL.', 'GetCountries'),

    # ('Show me cross listings for AAPL.', 'GetCrossListings'),
    # ('Show me crsi for AAPL.', 'GetTimeSeriesCrsi'),
    ('Show me cryptocurrencies list for BTC/USD.', 'GetCryptocurrencies'),  # fixed-error
    ('Show me cryptocurrency exchanges', 'GetCryptocurrencyExchanges'),  # fixed-error
    ('Show me currency conversion for EUR/USD.', 'GetCurrencyConversion'),  # fixed-error
    ('Show me dema for AAPL.', 'GetTimeSeriesDema'),  # fixed-error
    # ('Show me direct holders for AAPL.', 'GetDirectHolders'),
    ('Calculate DIV indicator for AAPL.', 'GetTimeSeriesDiv'),  # fixed-error
    # ('Show me dividends for AAPL.', 'GetDividends'),
    # # ('Show me dividends calendar for AAPL.', 'GetDividendsCalendar'),  # skipped-error

    # ('Show me dpo for AAPL.', 'GetTimeSeriesDpo'),
    # ('Show me dx for AAPL.', 'GetTimeSeriesDx'),
    # ('Show me earliest timestamp for AAPL.', 'GetEarliestTimestamp'),
    # ('Show me earnings for AAPL.', 'GetEarnings'),
    # ('Show me earnings calendar for AAPL.', 'GetEarningsCalendar'),
    # ('Show me earnings estimate for AAPL.', 'GetEarningsEstimate'),
    # ('Show me edgar filings archive for AAPL.', 'GetEdgarFilingsArchive'),
    # ('Show me ema for AAPL.', 'GetTimeSeriesEma'),
    # ('Show me end of day price for AAPL.', 'GetEod'),
    # ('Show me eps revisions for AAPL.', 'GetEpsRevisions'),

    # ('Show me eps trend for AAPL.', 'GetEpsTrend'),
    ('Show me ETFs for SPY on NYSE.', 'GetEtf'),  # fixed-error
    # ('Show me etfs family list for AAPL.', 'GetETFsFamily'),
    # ('Show me etfs list for AAPL.', 'GetETFsList'),
    ('Show me ETF types available in the United States.', 'GetETFsType'),  # fixed-error
    ('Show me all data for AAPL.', 'GetETFsWorld'), # error
    ('Show me composition for AAPL.', 'GetETFsWorldComposition'), # error
    ('Show me performance for AAPL.', 'GetETFsWorldPerformance'), # error
    ('Show me risk for AAPL.', 'GetETFsWorldRisk'),  # error
    # ('Show me a summary for the SPY ETF.', 'GetETFsWorldSummary'),  # strange-error !!!

    ('Show me exchange rate for AAPL.', 'GetExchangeRate'), # error
    # ('Show me exchange schedule for AAPL.', 'GetExchangeSchedule'),
    ('Show me exchanges for AAPL.', 'GetExchanges'), # error
    # ('Show me exp for AAPL.', 'GetTimeSeriesExp'),
    # ('Show me floor for AAPL.', 'GetTimeSeriesFloor'),
    ('Show me forex pairs list for AAPL.', 'GetForexPairs'), # error
    # ('Show me fund holders for AAPL.', 'GetFundHolders'),
    # ('Show me funds list for AAPL.', 'GetFunds'),
    # ('Show me growth estimates for AAPL.', 'GetGrowthEstimates'),
    # ('Show me heikinashicandles for AAPL.', 'GetTimeSeriesHeikinashiCandles'),

    #####################

    # ('Show me hlc3 for AAPL.', 'GetTimeSeriesHlc3'),
    # ('Show me ht_dcperiod for AAPL.', 'GetTimeSeriesHtDcPeriod'),
    # ('Show me ht_dcphase for AAPL.', 'GetTimeSeriesHtDcPhase'),
    # ('Show me ht_phasor for AAPL.', 'GetTimeSeriesHtPhasor'),
    # ('Show me ht_sine for AAPL.', 'GetTimeSeriesHtSine'),
    # ('Show me ht_trendline for AAPL.', 'GetTimeSeriesHtTrendline'),
    # ('Show me ht_trendmode for AAPL.', 'GetTimeSeriesHtTrendMode'),
    # ('Show me ichimoku for AAPL.', 'GetTimeSeriesIchimoku'),
    # ('Show me income statement for AAPL.', 'GetIncomeStatement'),
    # ('Show me income statement consolidated for AAPL.', 'GetIncomeStatementConsolidated'),
    # ('Show me insider transactions for AAPL.', 'GetInsiderTransactions'),
    # ('Show me institutional holders for AAPL.', 'GetInstitutionalHolders'),
    # ('Show me instrument type for AAPL.', 'GetInstrumentType'),
    # ('Show me intervals list for AAPL.', 'GetIntervals'),
    # ('Show me ipo calendar for AAPL.', 'GetIpoCalendar'),
    # ('Show me kama for AAPL.', 'GetTimeSeriesKama'),
    # ('Show me keltner for AAPL.', 'GetTimeSeriesKeltner'),
    # ('Show me key executives for AAPL.', 'GetKeyExecutives'),
    # ('Show me kst for AAPL.', 'GetTimeSeriesKst'),
    # ('Show me last changes for AAPL.', 'GetLastChanges'),
    # ('Show me linearreg for AAPL.', 'GetTimeSeriesLinearReg'),
    # ('Show me linearregangle for AAPL.', 'GetTimeSeriesLinearRegAngle'),
    # ('Show me linearregintercept for AAPL.', 'GetTimeSeriesLinearRegIntercept'),
    # ('Show me linearregslope for AAPL.', 'GetTimeSeriesLinearRegSlope'),
    # ('Show me ln for AAPL.', 'GetTimeSeriesLn'),
    # ('Show me log10 for AAPL.', 'GetTimeSeriesLog10'),
    # ('Show me logo for AAPL.', 'GetLogo'),
    # ('Show me ma for AAPL.', 'GetTimeSeriesMa'),
    # ('Show me macd for AAPL.', 'GetTimeSeriesMacd'),
    # ('Show me macd slope for AAPL.', 'GetTimeSeriesMacdSlope'),
    # ('Show me macdext for AAPL.', 'GetTimeSeriesMacdExt'),
    # ('Show me mama for AAPL.', 'GetTimeSeriesMama'),
    # ('Show me market capitalization for AAPL.', 'GetMarketCap'),
    # ('Show me market movers for AAPL.', 'GetMarketMovers'),
    # ('Show me market state for AAPL.', 'GetMarketState'),
    # ('Show me overlap studies for AAPL.', 'GetTimeSeriesMaVp'),
    # ('Show me max for AAPL.', 'GetTimeSeriesMax'),
    # ('Show me maxindex for AAPL.', 'GetTimeSeriesMaxIndex'),
    # ('Show me mcginley_dynamic for AAPL.', 'GetTimeSeriesMcGinleyDynamic'),
    # ('Show me medprice for AAPL.', 'GetTimeSeriesMedPrice'),
    # ('Show me mfi for AAPL.', 'GetTimeSeriesMfi'),
    # ('Show me midpoint for AAPL.', 'GetTimeSeriesMidPoint'),
    # ('Show me midprice for AAPL.', 'GetTimeSeriesMidPrice'),
    # ('Show me min for AAPL.', 'GetTimeSeriesMin'),
    # ('Show me minindex for AAPL.', 'GetTimeSeriesMinIndex'),
    # ('Show me minmax for AAPL.', 'GetTimeSeriesMinMax'),
    # ('Show me minmaxindex for AAPL.', 'GetTimeSeriesMinMaxIndex'),
    # ('Show me minus_di for AAPL.', 'GetTimeSeriesMinusDI'),
    # ('Show me minus_dm for AAPL.', 'GetTimeSeriesMinusDM'),
    # ('Show me mom for AAPL.', 'GetTimeSeriesMom'),
    # ('Show me mult for AAPL.', 'GetTimeSeriesMult'),
    # ('Show me mfs family list for AAPL.', 'GetMutualFundsFamily'),
    # ('Show me mfs list for AAPL.', 'GetMutualFundsList'),
    # ('Show me mfs type list for AAPL.', 'GetMutualFundsType'),
    # ('Show me all data for AAPL.', 'GetMutualFundsWorld'),
    # ('Show me composition for AAPL.', 'GetMutualFundsWorldComposition'),
    # ('Show me performance for AAPL.', 'GetMutualFundsWorldPerformance'),
    # ('Show me purchase info for AAPL.', 'GetMutualFundsWorldPurchaseInfo'),
    # ('Show me ratings for AAPL.', 'GetMutualFundsWorldRatings'),
    # ('Show me risk for AAPL.', 'GetMutualFundsWorldRisk'),
    # ('Show me summary for AAPL.', 'GetMutualFundsWorldSummary'),
    # ('Show me sustainability for AAPL.', 'GetMutualFundsWorldSustainability'),
    # ('Show me natr for AAPL.', 'GetTimeSeriesNatr'),
    # ('Show me obv for AAPL.', 'GetTimeSeriesObv'),
    # ('Show me percent_b for AAPL.', 'GetTimeSeriesPercent_B'),
    # ('Show me pivot_points_hl for AAPL.', 'GetTimeSeriesPivotPointsHL'),
    # ('Show me plus_di for AAPL.', 'GetTimeSeriesPlusDI'),
    # ('Show me plus_dm for AAPL.', 'GetTimeSeriesPlusDM'),
    # ('Show me ppo for AAPL.', 'GetTimeSeriesPpo'),
    # ('Show me real-time price for AAPL.', 'GetPrice'),
    # ('Show me price target for AAPL.', 'GetPriceTarget'),
    # ('Show me profile for AAPL.', 'GetProfile'),
    # ('Show me quote for AAPL.', 'GetQuote'),
    # ('Show me recommendations for AAPL.', 'GetRecommendations'),
    # ('Show me revenue estimate for AAPL.', 'GetRevenueEstimate'),
    # ('Show me roc for AAPL.', 'GetTimeSeriesRoc'),
    # ('Show me rocp for AAPL.', 'GetTimeSeriesRocp'),
    # ('Show me rocr for AAPL.', 'GetTimeSeriesRocr'),
    # ('Show me rocr100 for AAPL.', 'GetTimeSeriesRocr100'),
    # ('Show me rsi for AAPL.', 'GetTimeSeriesRsi'),
    # ('Show me rvol for AAPL.', 'GetTimeSeriesRvol'),
    # ('Show me sanctioned entities for AAPL.', 'GetSourceSanctionedEntities'),
    # ('Show me sar for AAPL.', 'GetTimeSeriesSar'),
    # ('Show me sarext for AAPL.', 'GetTimeSeriesSarExt'),
    # ('Show me sma for AAPL.', 'GetTimeSeriesSma'),
    # ('Show me splits for AAPL.', 'GetSplits'),
    # ('Show me splits calendar for AAPL.', 'GetSplitsCalendar'),
    # ('Show me sqrt for AAPL.', 'GetTimeSeriesSqrt'),
    # ('Show me statistics for AAPL.', 'GetStatistics'),
    # ('Show me stddev for AAPL.', 'GetTimeSeriesStdDev'),
    # ('Show me stoch for AAPL.', 'GetTimeSeriesStoch'),
    # ('Show me stochf for AAPL.', 'GetTimeSeriesStochF'),
    # ('Show me stochrsi for AAPL.', 'GetTimeSeriesStochRsi'),
    # ('Show me stocks list for AAPL.', 'GetStocks'),
    # ('Show me sub for AAPL.', 'GetTimeSeriesSub'),
    # ('Show me sum for AAPL.', 'GetTimeSeriesSum'),
    # ('Show me supertrend for AAPL.', 'GetTimeSeriesSuperTrend'),
    # ('Show me supertrend heikinashicandles for AAPL.', 'GetTimeSeriesSuperTrendHeikinAshiCandles'),
    # ('Show me symbol search for AAPL.', 'GetSymbolSearch'),
    # ('Show me t3ma for AAPL.', 'GetTimeSeriesT3ma'),
    # ('Show me tax information for AAPL.', 'GetTaxInfo'),
    # ('Show me technical indicators interface for AAPL.', 'GetTechnicalIndicators'),
    # ('Show me tema for AAPL.', 'GetTimeSeriesTema'),
    # ('Show me time series for AAPL.', 'GetTimeSeries'),
    # ('Show me time series cross for AAPL.', 'GetTimeSeriesCross'),
    # ('Show me trange for AAPL.', 'GetTimeSeriesTRange'),
    # ('Show me trima for AAPL.', 'GetTimeSeriesTrima'),
    # ('Show me tsf for AAPL.', 'GetTimeSeriesTsf'),
    # ('Show me typprice for AAPL.', 'GetTimeSeriesTypPrice'),
    # ('Show me ultosc for AAPL.', 'GetTimeSeriesUltOsc'),
    # ('Show me var for AAPL.', 'GetTimeSeriesVar'),
    # ('Show me vwap for AAPL.', 'GetTimeSeriesVwap'),
    # ('Show me wclprice for AAPL.', 'GetTimeSeriesWclPrice'),
    # ('Show me willr for AAPL.', 'GetTimeSeriesWillR'),
    # ('Show me wma for AAPL.', 'GetTimeSeriesWma'),
]
